"""third

Revision ID: 5fb0705d876a
Revises: 60efb81617d4
Create Date: 2024-01-13 21:06:56.369175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb0705d876a'
down_revision = '60efb81617d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
