"""second one

Revision ID: 60efb81617d4
Revises: 1a660c242acb
Create Date: 2024-01-13 20:52:20.073097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60efb81617d4'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
